import random
import matplotlib.pyplot as plt

# A - this is taken from the covid ncbi from last lab
dna = """CTTAAAGAATTTTTCTATCTATAGATAGAGAATTTTCTTATTTAGACTTTGTGTCTACTCTTCTCAACTA
AACGAAATTTTTCTAGTGCTGTCATTTGTTATGGCAGTCCTAGTGTAATTGAAATTTCGTCAAGTTTGTA
AACTGGTTAGGCAAGTGTTGTATTTTCTGTGTCTAAGCACTGGTGATTCTGTTCACTAGTGCATACATTG
ATATTTAAGTGGTGTTCCGTCACTGCTTATTGTGGAAGCAACGTTCTGTCGTTGTGGAAACCAATAACTG
CTAACCATGTTTTACAATCAAGTGACACTTGCTGTTGCAAGTGATTCGGAAATTTCAGGTTTTGGTTTTG
CCATTCCTTCTGTAGCCGTTCGCACCTATAGCGAAGCCGCTGCACAAGGTTTTCAGGCATGCCGTTTTGT
TGCTTTTGGCTTACAGGATTGTGTAACCGGTATTAATGATGATGATTATGTCATTGCATTGACTGGTACT
AATCAGCTCTGTGCCAAAATTTTACCTTTTTCTGATAGACCCCTTAATTTGCGAGGTTGGCTCATTTTTT
CTAACAGCAATTATGTTCTTCAGGACTTTGATGTTGTTTTTGGCCATGGTGCAGGAAGTGTGGTTTTTGT
GGATAAGTACATGTGTGGTTTTGATGGTAAACCTGTGTTACCTAAAAACATGTGGGAATTTAGGGATTAC
TTTAATAATAATACTGATAGTATTGTTATTGGTGGTGTCACTTATCAACTAGCATGGGATGTTATACGTA
AAGACCTTTCTTATGAACAGCAAAATGTTTTAGCCATTGAGAGCATTCATTACCTTGGTACTACAGGTCA
TACTTTGAAGTCTGGTTGCAAACTTACTAATGCTAAGCCGCCTAAATATTCTTCTAAGGTTGTTTTGAGT
GGTGAATGGAATGCTGTGTATAGGGCGTTTGGTTCACCATTTATTACAAATGGTATGTCATTGCTAGATA
TAATTGTTAAACCAGTTTTCTTTAATGCTTTTGTTAAATGCAATTGTGGTTCTGAGAGTTGGAGTGTTGG
TGCATGGGATGGTTACTTATCTTCTTGTTGTGGCACACCTGCTAAGAAACTTTGTGTTGTTCCTGGTAAT
GTCGTTCCTGGTGATGTGATCATCACCTCAACTAGTGCTGGTTGTGGTGTTAAATACTATGCTGGCTTAG
TTGTTAAACATATTACTAACATTACTGGTGTGTCTTTATGGCGTGTTACAGCTGTTCATTCTGATGGAAT
GTTTGTGGCATCATCTTCTTATGATGCACTCTTGCATAGAAATTCATTAGACCCTTTTTGCTTTGATGTT
AACACTTTACTTTCTAATCAATTACGTCTAGCTTTTCTTGGTGCTTCTGTTACAGAAGATGTTAAATTTG
CTGCTAGCACTGGTGTTATTGACATTAGTGCTGGTATGTTTGGTCTTTACGATGACATATTGACAAACAA
TAAACCTTGGTTTGTACGCAAAGCTTCTGGGCTTTTTGATGCAATCTGGGATGCTTTTGTTGCCGCTATT
AAGCTTGTACCAACTACTACTGGTGTTTTGGTTAGGTTTGTTAAGTCTATTGCTTCAACTGTTTTAACTG
TCTCTAATGGTGTTATTATTATGTGTGCAGATGTTCCAGATGCTTTTCAATCAGTTTATCGCACATTTAC
ACAAGCTATTTGTGCTGCATTTGATTTTTCTTTAGATGTATTTAAAATTGGTGATGTTAAATTTAAACGA
CTTGGTGATTATGTTCTTACTGAAAACGCTCTTGTTCGTTTGACTACTGAAGTTGTTCGTGGTGTTCGTG
ATGCTCGCATAAAGAAAGCCATGTTTACTAAAGTAGTTGTAGGTCCTACAACTGAAGTTAAGTTTTCTGT
TATTGAACTTGCCACTGTTAATTTGCGTCTTGTTGATTGTGCACCTGTAGTTTGCCCTAAAGGTAAGATT
GTTGTTATTGCTGGACAAGCTTTTTTCTATAGTGGTGGTTTTTATCGTTTTATGGTTGATCCTACAACTG
TATTAAATGATCCTGTTTTTACTGGTGATTTATTCTACACTATTAAGTTTAGTGGTTTTAAGCTTGATGG
TTTTAACCATCAGTTTGTTACTGCTAGTTCTGCTACAGATGCCATTATTGCTGTTGAGCTGTTGTTATTG
GATTTTAAAACTGCAGTTTTTGTGTACACATGTGTGGTTGATGGCTGTAGTGTCATTGTTAGACGTGATG
CTACATTCGCTACACATGTGTGTTTTAAGGACTGTTATAATGTTTGGGAGCAATTCTGCATTGATAATTG
TGGTGAGCCATGGTTTTTGACTGATTATAATGCTATCTTGCAGAGTAATAACCCTCAATGTGCTATTGTT
CAAGCATCAGAGTCTAAAGTTTTGCTTGAGAGGTTTTTACCTAAGTGTCCTGAAATACTGTTGAGTATTG
ATGATGGCCATTTATGGAATCTTTTTGTTGAAAAGTTTAATTTTGTTACAGATTGGTTAAAAACTCTTAA
GCTTACACTTACTTCTAATGGTCTTTTAGGTAATTGTGCCAAACGTTTTAGACGTGTTTTGGTAAAATTG
CTTGATGTCTATAATGGTTTTCTTGAAACTGTCTGTAGTGTCGCATACACTGCTGGTGTTTGCATCAAAT
ATTATGCTGTTAATGTTCCATATGTAGTTATTAGTGGTTTTGTAAGTCGTGTAATTCGTAGAGAAAGGTG
TGACATGACTTTTCCTTGTGTTAGTTGTGTCACCTTTTTCTATGAATTTTTAGACACTTGTTTTGGTGTT
AGTAAACCTAATGCCATTGATGTTGAACATTTAGAGCTTAAAGAAACTGTTTTTGTTGAACCTAAGGATG
GTGGTCAATTTTTTGTTTCTGGTGATTATCTTTGGTATGTTGTAGATGACATTTATTATCCAGCTTCATG
TAATGGTGTATTGCCTGTTGCTTTTACAAAATTAGCTGGTGGTAAAATATCTTTTTCTGATGATGTTATA
GTTCATGATGTTGAACCTACCCATAAAGTCAAGCTCATATTTGAGTTTGAAGATGATGTTGTTACCAGTC
TTTGTAAGAAGAGTTTTGGTAAGTCCATTATTTATACAGGTGATTGGGAAGGTCTACATGAAGTTCTTAC
ATCTGCAATGAATGTCATTGGGCAACATATTAAGTTGCCACAATTTTATATTTATGATGAAGAGGGTGGT
TATGATGTTTCTAAACCAGTTATGATTTCACAATGGCCTATTAGTAATGATAGTAATGGTTGTGTTGTTG""".replace("\n", "")[:3000]  

# B
samples = []
positions = []
for _ in range(2000):
    start = random.randint(0, len(dna) - 150)
    end = start + random.randint(100, 150)
    samples.append(dna[start:end])
    positions.append((start, end))

# C
reconstructed = samples[0]
for s in samples[1:]:
    for overlap in range(150, 9, -1):  # overlap must be ≥10
        if reconstructed.endswith(s[:overlap]):
            reconstructed += s[overlap:]
            break

# D
print("\n ORIGINAL DNA (first 200 bases):")
print(dna[:200])
print("\n RECONSTRUCTED DNA (first 200 bases):")
print(reconstructed[:200])

print("\nOriginal length:", len(dna))
print("Reconstructed length:", len(reconstructed))

# E
plt.figure(figsize=(12, 5))
for i, (start, end) in enumerate(random.sample(positions, 100)):  # show 80 random reads
    plt.hlines(i, start, end, colors='tab:blue', lw=2)

plt.title("Random DNA samples (each line = one fragment)")
plt.xlabel("Position along original DNA (0 → 2000)")
plt.ylabel("Sample index")
plt.show()

# F
print("\n MAIN PROBLEM:")
print("""
As you can see, the reconstructed DNA is much shorter.
This happens because:
- Random samples overlap inconsistently.
- Many fragments don't align perfectly (especially in repetitive regions).
- Some areas of the DNA are missing completely (no samples cover them).
""")
